# -*- coding: utf-8 -*-
"""incident_cleaner

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1btidCYqBdB7EbCM15jxzSDnDDY-nBSdS
"""

import re
from sklearn.base import BaseEstimator, TransformerMixin

class IncidentCleaner(BaseEstimator, TransformerMixin):
    def __init__(self, categories=None):
        self.categories = categories or []

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        cleaned = []
        for text in X:
            if not isinstance(text, str):
                text = str(text)
            for cat in self.categories:
                text = re.sub(rf"\b{cat}\b", "", text, flags=re.IGNORECASE)
            text = re.sub(r"\s+", " ", text).strip()
            cleaned.append(text)
        return cleaned